
services:
  frontend:
    build: ./client
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
  
  backend:
    build: ./server
    ports:
      - "3000:3000"
  
  
